# Generated by Django 4.1.1 on 2022-09-25 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_albums', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('favorites', models.ManyToManyField(blank=True, null=True, related_name='favor_album', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatars', verbose_name='Аватар')),
                ('caption', models.CharField(max_length=120, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('public', models.BooleanField(default=1)),
                ('album', models.ManyToManyField(blank=True, null=True, related_name='album_photos', to='webapp.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('favorites', models.ManyToManyField(blank=True, null=True, related_name='favor_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
