# Generated by Django 4.1.1 on 2022-09-25 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favor_album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='album_photos', to='webapp.album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favor_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
